### PR TITLE
new logging implemented. It uses std Qt messaging. It also fixes tens of

### PR DESCRIPTION
**Pull request by pvanek**
compiler warning about endl use

### CODE REVIEW

**Comment by coozoo** [comment]
Yeah nice. 
But how about to replace qDebug() with qInfo() ? 
because in some distros qDebug is disabled system wide configuration and as result will be no messages.

**Comment by pvanek** [comment]
yes, that's exactly what's implemented in https://github.com/coozoo/qtjsondiff/pull/19/files#diff-b42ca2a4cb7012cceab2fac925eec74ca95287d1784cbb6e17855b9f743e3211R19 - not to pollute stdout with debugging messages in production builds. It still prints debug strings in your debug/dev build, but the final product prints out just info, fatal, and critical. It's very kind to users who run the app from terminals for example

**Comment by coozoo** [comment]
Nope it will not print on Fedora for example (and as result suppose rhel and centos the same)
because of such configuration

```
cat /usr/share/qt5/qtlogging.ini
[Rules]
*.debug=false
qt.qpa.xcb.xcberror.warning=false
```

So it doesn't matter if I'm building debug or release in anyway all debug messages in these distros are suppressed.

**Comment by pvanek** [comment]
d'oh. That's something.

Can you test one thing, please? Can you compile this branch with `QLoggingCategory::setFilterRules("*.debug=true");` inside the main function?

As example in
```
#include <QCoreApplication>
#include <QLoggingCategory>
int main(int argc, char *argv[])
{
  QCoreApplication a(argc, argv);
  QLoggingCategory::setFilterRules("*.debug=true");
  qDebug() << "Debugging;
  a.exit();
}
```

I'll update the PR accordingly if it will work in Fedora

reference link:
https://bugzilla.redhat.com/show_bug.cgi?id=1227295

**Comment by coozoo** [comment]
Oh nice trick and it works just spamming a lot of events (most of them cursor moves)

can you update that and change it a bit to something like this?

`    QLoggingCategory::setFilterRules("*.debug=true\nqt.*.debug=false");`

**Comment by pvanek** [comment]
updated

**Pull request merged**
